from functions.ds_color import color
from functions.ds_date import date
from functions.ds_emoji import emoji
from functions.ds_help import help
from functions.ds_hug import hug
from functions.ds_random import random
from functions.ds_splash import splash
from functions.ds_yt import yt
from functions.ds_info import info
from functions.ds_mailing import mailing
from functions.ds_search import search
from functions.ds_bite import bite
from functions.ds_delete import delete
from functions.ds_game import game